## Preprocessing

In [60]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [61]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'. Drop "ORGANIZATION" and "USE_CASE"
application_df = application_df.drop(columns = ["EIN", "NAME", "ORGANIZATION", "USE_CASE"])

In [62]:
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,1,0,N,5000,1
1,T3,Independent,C2000,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,1,0,N,5000,0
3,T3,CompanySponsored,C2000,1,10000-24999,N,6692,1
4,T3,Independent,C1000,1,100000-499999,N,142590,1

In [63]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [64]:
# Look at APPLICATION_TYPE value counts for binning
application_counts = application_df["APPLICATION_TYPE"].value_counts()
application_counts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [88]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
cutoff = 100
application_types_to_replace = application_counts[application_counts < cutoff].index.tolist()

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [66]:
# Look at CLASSIFICATION value counts for binning
classification_counts = application_df["CLASSIFICATION"].value_counts()
classification_counts

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [67]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classification_counts[classification_counts > 1]

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [89]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
cutoff = 700
classifications_to_replace = classification_counts[classification_counts < cutoff].index.tolist()

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [90]:
# Convert categorical data to numeric with `pd.get_dummies`
dummies_df = pd.get_dummies(application_df)
dummies_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [91]:
# Split our preprocessed data into our features and target arrays
X = dummies_df.drop(["IS_SUCCESSFUL"], axis = 1).values
y = dummies_df["IS_SUCCESSFUL"].values
# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [92]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [93]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train[0])
hidden_nodes_layer1 = 100
hidden_nodes_layer2 = 70
hidden_nodes_layer3 = 50
hidden_nodes_layer4 = 30

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units = hidden_nodes_layer1, input_dim = number_input_features,
                            activation = "relu"))
# Second hidden layer
nn.add(tf.keras.layers.Dense(units = hidden_nodes_layer2,
                            activation = "relu"))
# Third hidden layer
nn.add(tf.keras.layers.Dense(units = hidden_nodes_layer3,
                            activation = "tanh"))
# Third hidden layer
nn.add(tf.keras.layers.Dense(units = hidden_nodes_layer4,
                            activation = "tanh"))

# Output layer
nn.add(tf.keras.layers.Dense(units = 1, activation = "sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential_14"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_59 (Dense)            (None, 100)               3500

 dense_60 (Dense)            (None, 70)                7070

 dense_61 (Dense)            (None, 50)                3550

 dense_62 (Dense)            (None, 30)                1530

 dense_63 (Dense)            (None, 1)                 31

=================================================================
Total params: 15,681
Trainable params: 15,681
Non-trainable params: 0
_________________________________________________________________

In [94]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [95]:
# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs=180)

Epoch 1/180
804/804 [==============================] - 2s 1ms/step - loss: 0.5745 - accuracy: 0.7187
Epoch 2/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5668 - accuracy: 0.7251
Epoch 3/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5652 - accuracy: 0.7266
Epoch 4/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5639 - accuracy: 0.7278
Epoch 5/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5636 - accuracy: 0.7272
Epoch 6/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5628 - accuracy: 0.7279
Epoch 7/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5626 - accuracy: 0.7273
Epoch 8/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5618 - accuracy: 0.7282
Epoch 9/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5617 - accuracy: 0.7278
Epoch 10/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5616 - accuracy: 0.7291
Epoch 11/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5609 - accuracy: 0.7287
Epoch 12/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5606 - accuracy: 0.7281
Epoch 13/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5602 - accuracy: 0.7285
Epoch 14/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5604 - accuracy: 0.7284
Epoch 15/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5599 - accuracy: 0.7293
Epoch 16/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5594 - accuracy: 0.7296
Epoch 17/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5599 - accuracy: 0.7290
Epoch 18/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5595 - accuracy: 0.7290
Epoch 19/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5591 - accuracy: 0.7296
Epoch 20/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5590 - accuracy: 0.7293
Epoch 21/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5587 - accuracy: 0.7299
Epoch 22/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5590 - accuracy: 0.7291
Epoch 23/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5586 - accuracy: 0.7293
Epoch 24/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5586 - accuracy: 0.7301
Epoch 25/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5582 - accuracy: 0.7304
Epoch 26/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5580 - accuracy: 0.7305
Epoch 27/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5580 - accuracy: 0.7297
Epoch 28/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5582 - accuracy: 0.7304
Epoch 29/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5580 - accuracy: 0.7295
Epoch 30/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5576 - accuracy: 0.7301
Epoch 31/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5581 - accuracy: 0.7306
Epoch 32/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5577 - accuracy: 0.7304
Epoch 33/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5572 - accuracy: 0.7307
Epoch 34/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5573 - accuracy: 0.7301
Epoch 35/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5575 - accuracy: 0.7305
Epoch 36/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5569 - accuracy: 0.7303
Epoch 37/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5578 - accuracy: 0.7299
Epoch 38/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5577 - accuracy: 0.7301
Epoch 39/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5576 - accuracy: 0.7307
Epoch 40/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5568 - accuracy: 0.7306
Epoch 41/180
804/804 [==============================] - 1s 2ms/step - loss: 0.5567 - accuracy: 0.7309
Epoch 42/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5574 - accuracy: 0.7307
Epoch 43/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5575 - accuracy: 0.7297
Epoch 44/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5568 - accuracy: 0.7301
Epoch 45/180
804/804 [==============================] - 1s 2ms/step - loss: 0.5571 - accuracy: 0.7313
Epoch 46/180
804/804 [==============================] - 1s 2ms/step - loss: 0.5566 - accuracy: 0.7311
Epoch 47/180
804/804 [==============================] - 1s 2ms/step - loss: 0.5566 - accuracy: 0.7305
Epoch 48/180
804/804 [==============================] - 1s 2ms/step - loss: 0.5567 - accuracy: 0.7310
Epoch 49/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5566 - accuracy: 0.7308
Epoch 50/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5569 - accuracy: 0.7307
Epoch 51/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5569 - accuracy: 0.7303
Epoch 52/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5568 - accuracy: 0.7303
Epoch 53/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5565 - accuracy: 0.7308
Epoch 54/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5566 - accuracy: 0.7308
Epoch 55/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5567 - accuracy: 0.7304
Epoch 56/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5562 - accuracy: 0.7308
Epoch 57/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5564 - accuracy: 0.7306
Epoch 58/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5565 - accuracy: 0.7308
Epoch 59/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5562 - accuracy: 0.7304
Epoch 60/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5561 - accuracy: 0.7310
Epoch 61/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5562 - accuracy: 0.7306
Epoch 62/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5561 - accuracy: 0.7310
Epoch 63/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5568 - accuracy: 0.7301
Epoch 64/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5565 - accuracy: 0.7304
Epoch 65/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5562 - accuracy: 0.7303
Epoch 66/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5567 - accuracy: 0.7301
Epoch 67/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5560 - accuracy: 0.7307
Epoch 68/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5563 - accuracy: 0.7307
Epoch 69/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5561 - accuracy: 0.7308
Epoch 70/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5567 - accuracy: 0.7305
Epoch 71/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5563 - accuracy: 0.7307
Epoch 72/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5561 - accuracy: 0.7303
Epoch 73/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5564 - accuracy: 0.7303
Epoch 74/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5564 - accuracy: 0.7305
Epoch 75/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5562 - accuracy: 0.7304
Epoch 76/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5562 - accuracy: 0.7303
Epoch 77/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5561 - accuracy: 0.7301
Epoch 78/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5562 - accuracy: 0.7314
Epoch 79/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5565 - accuracy: 0.7309
Epoch 80/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5561 - accuracy: 0.7311
Epoch 81/180

804/804 [==============================] - 1s 1ms/step - loss: 0.5561 - accuracy: 0.7312
Epoch 82/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5563 - accuracy: 0.7302
Epoch 83/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5565 - accuracy: 0.7311
Epoch 84/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5558 - accuracy: 0.7312
Epoch 85/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5563 - accuracy: 0.7310
Epoch 86/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5557 - accuracy: 0.7311
Epoch 87/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5561 - accuracy: 0.7300
Epoch 88/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5554 - accuracy: 0.7311
Epoch 89/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5556 - accuracy: 0.7313
Epoch 90/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5557 - accuracy: 0.7311
Epoch 91/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5562 - accuracy: 0.7311
Epoch 92/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5558 - accuracy: 0.7314
Epoch 93/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5564 - accuracy: 0.7307
Epoch 94/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5562 - accuracy: 0.7312
Epoch 95/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5562 - accuracy: 0.7308
Epoch 96/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5559 - accuracy: 0.7313
Epoch 97/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5558 - accuracy: 0.7310
Epoch 98/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5562 - accuracy: 0.7313
Epoch 99/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5562 - accuracy: 0.7305
Epoch 100/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5565 - accuracy: 0.7304
Epoch 101/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5564 - accuracy: 0.7307
Epoch 102/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5560 - accuracy: 0.7310
Epoch 103/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5557 - accuracy: 0.7307
Epoch 104/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5561 - accuracy: 0.7308
Epoch 105/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5560 - accuracy: 0.7310
Epoch 106/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5558 - accuracy: 0.7313
Epoch 107/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5557 - accuracy: 0.7312
Epoch 108/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5558 - accuracy: 0.7311
Epoch 109/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5558 - accuracy: 0.7312
Epoch 110/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5558 - accuracy: 0.7313
Epoch 111/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5556 - accuracy: 0.7313
Epoch 112/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5555 - accuracy: 0.7313
Epoch 113/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5559 - accuracy: 0.7316
Epoch 114/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5558 - accuracy: 0.7307
Epoch 115/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5559 - accuracy: 0.7311
Epoch 116/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5560 - accuracy: 0.7310
Epoch 117/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5558 - accuracy: 0.7310
Epoch 118/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5554 - accuracy: 0.7315
Epoch 119/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5556 - accuracy: 0.7310
Epoch 120/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5557 - accuracy: 0.7310
Epoch 121/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5560 - accuracy: 0.7308
Epoch 122/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5560 - accuracy: 0.7310
Epoch 123/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5564 - accuracy: 0.7302
Epoch 124/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5560 - accuracy: 0.7291
Epoch 125/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5567 - accuracy: 0.7295
Epoch 126/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5570 - accuracy: 0.7296
Epoch 127/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5566 - accuracy: 0.7306
Epoch 128/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5559 - accuracy: 0.7316
Epoch 129/180
804/804 [==============================] - 1s 2ms/step - loss: 0.5562 - accuracy: 0.7294
Epoch 130/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5557 - accuracy: 0.7310
Epoch 131/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5559 - accuracy: 0.7309
Epoch 132/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5556 - accuracy: 0.7311
Epoch 133/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5565 - accuracy: 0.7308
Epoch 134/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5562 - accuracy: 0.7309
Epoch 135/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5557 - accuracy: 0.7309
Epoch 136/180
804/804 [==============================] - 1s 2ms/step - loss: 0.5559 - accuracy: 0.7309
Epoch 137/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5565 - accuracy: 0.7309
Epoch 138/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5557 - accuracy: 0.7310
Epoch 139/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5558 - accuracy: 0.7313
Epoch 140/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5559 - accuracy: 0.7311
Epoch 141/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5555 - accuracy: 0.7311
Epoch 142/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5565 - accuracy: 0.7306
Epoch 143/180
804/804 [==============================] - 1s 2ms/step - loss: 0.5571 - accuracy: 0.7308
Epoch 144/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5572 - accuracy: 0.7309
Epoch 145/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5564 - accuracy: 0.7315
Epoch 146/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5560 - accuracy: 0.7308
Epoch 147/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5563 - accuracy: 0.7310
Epoch 148/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5557 - accuracy: 0.7306
Epoch 149/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5561 - accuracy: 0.7311
Epoch 150/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5565 - accuracy: 0.7308
Epoch 151/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5561 - accuracy: 0.7309
Epoch 152/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5564 - accuracy: 0.7308
Epoch 153/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5569 - accuracy: 0.7307
Epoch 154/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5565 - accuracy: 0.7309
Epoch 155/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5566 - accuracy: 0.7309
Epoch 156/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5562 - accuracy: 0.7306
Epoch 157/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5573 - accuracy: 0.7307
Epoch 158/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5568 - accuracy: 0.7304
Epoch 159/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5565 - accuracy: 0.7312
Epoch 160/180

804/804 [==============================] - 1s 1ms/step - loss: 0.5578 - accuracy: 0.7303
Epoch 161/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5573 - accuracy: 0.7301
Epoch 162/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5568 - accuracy: 0.7301
Epoch 163/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5574 - accuracy: 0.7310
Epoch 164/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5577 - accuracy: 0.7290
Epoch 165/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5571 - accuracy: 0.7304
Epoch 166/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5576 - accuracy: 0.7308
Epoch 167/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5566 - accuracy: 0.7311
Epoch 168/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5565 - accuracy: 0.7310
Epoch 169/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5564 - accuracy: 0.7308
Epoch 170/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5570 - accuracy: 0.7310
Epoch 171/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5566 - accuracy: 0.7311
Epoch 172/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5567 - accuracy: 0.7303
Epoch 173/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5564 - accuracy: 0.7309
Epoch 174/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5565 - accuracy: 0.7312
Epoch 175/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5565 - accuracy: 0.7303
Epoch 176/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5563 - accuracy: 0.7304
Epoch 177/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5565 - accuracy: 0.7304
Epoch 178/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5564 - accuracy: 0.7312
Epoch 179/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5567 - accuracy: 0.7315
Epoch 180/180
804/804 [==============================] - 1s 1ms/step - loss: 0.5563 - accuracy: 0.7310

In [96]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5664 - accuracy: 0.7224 - 310ms/epoch - 1ms/step
Loss: 0.5664139986038208, Accuracy: 0.722449004650116

In [ ]:
# Experimented with dropping more columns, increasing the number of values for each bin,
# added more neurons/hidden layers, used different activation functions, and increased
# the number of epochs to the training regimen. However, the accuracy and loss did not change
# too much.

In [97]:
# Export our model to HDF5 file
nn.save('AlphabetSoupCharity_Optimization.h5')